fix: cluster user does not support modern managed resource (#29)
Error: "namespace":"","name":"demo","panic":"interface conversion: *v1alpha1.User is not resource.ModernManaged: missing method GetProviderConfigReference","panicGoValue"